JobScraper/urls.py
# from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls'))
]

mysite/jobs/urls.py
from django.urls import path

from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.fetch, name='fetch'),
    path('home/', views.home, name='home'),
    path('inbox/', views.inbox, name='inbox'),
    path('preferences/', views.preferences, name='preferences'),
    path('save_preferences/', views.save_preferences, name='save_preferences'),
    path('history/', views.history, name='history'),
    path('open_offer/', views.open_offer, name='open_offer'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls'))
]

mysite/jobs/models.py
from django.db import models


class Offer(models.Model):
    offer_title = models.CharField(max_length=200)
    offer_url = models.CharField(max_length=300)
    opened = models.BooleanField(default=False)


class Localization(models.Model):
    value = models.CharField(max_length=200)
    checked = models.BooleanField(default=False)


class Role(models.Model):
    value = models.CharField(max_length=200)
    name = models.CharField(max_length=200, default='')
    checked = models.BooleanField(default=False)


class Technology(models.Model):
    value = models.CharField(max_length=200)
    name = models.CharField(max_length=200, default='')
    checked = models.BooleanField(default=False)


class Experience(models.Model):
    value = models.CharField(max_length=200)
    name = models.CharField(max_length=200, default='')
    checked = models.BooleanField(default=False)

mysite/jobs/views.py
from django.shortcuts import render, redirect
from .methods import save_preferences_in_db, fetch_offers, open_offer_url
from .models import *


def home(request):
    if Offer.objects.filter(opened=0):
        notification = 1
    else:
        notification = 0
    print(notification)
    context = {'notification': notification}
    return render(request, 'jobs/home.html', context)


def inbox(request):
    new_offers = Offer.objects.filter(opened=0)
    context = {'new_offers': new_offers}
    return render(request, 'jobs/inbox.html', context)


def preferences(request):
    localizations = Localization.objects.order_by('id')
    roles = Role.objects.order_by('id')
    technologies = Technology.objects.order_by('id')
    experience = Experience.objects.order_by('id')
    context = {
        'localizations': localizations,
        'roles': roles,
        'technologies': technologies,
        'experience': experience
    }
    return render(request, 'jobs/preferences.html', context)


def save_preferences(request):
    if request.method == 'POST':
        save_preferences_in_db(request)

    return redirect('jobs:fetch')


def history(request):
    seen_before_offers = Offer.objects.filter(opened=1)
    context = {'seen_before_offers': seen_before_offers}
    return render(request, 'jobs/history.html', context)


def fetch(request):
    fetch_offers()
    return redirect('jobs:home')


def open_offer(request):
    if request.method == 'POST':
        offer_url = open_offer_url(request)
    else:
        offer_url = 'jobs:inbox'

    return redirect(offer_url)

mysite/jobs/templates/jobs/fetch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fetch</title>
</head>
<body>

<h1>Ładowanie</h1>

</body>
</html>

mysite/jobs/templates/jobs/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>History</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
<div id="content" class="main">
    <form class="input-group" action="{% url 'jobs:home' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="url" value=""/>
        <input class="btn btn-outline-secondary m-1 mb-1 rounded-1" type="submit" value="Wróć">
    </form>
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="display-3 text-muted" align="center">Przeglądane oferty</h1>
            <hr class="mt-3 mb-4">
            <br class="mt-5">
            {% if seen_before_offers %}
                {% for offer in seen_before_offers %}
                    <a class="btn btn-outline-secondary input-group mb-3" href="{{ offer.offer_url }}" target="_blank"
                       rel="noopener noreferrer">{{ offer.offer_title }}</a>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <br class="mt-3 mb-5">
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>
</html>

mysite/jobs/templates/jobs/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
<div id="content" class="main">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-5 display-1 text-muted" align="center">Job - Hunter</h1>
            <hr class="mt-3 mb-4">

            <br class="mt-5">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        {% if notification %}
                            <form id="inbox_form" action="{% url 'jobs:inbox' %}" method="post" align="right">
                                {% csrf_token %}
                                <input class="btn btn-outline-primary btn-lg" id="inbox_btn" type=submit
                                       value="Oferty">
                            </form>
                        {% else %}
                            <form id="inbox_form" action="{% url 'jobs:inbox' %}" method="post" align="right">
                                {% csrf_token %}
                                <input class="btn btn-outline-secondary btn-lg" id="inbox_btn" type=submit
                                       value="Oferty">
                            </form>
                        {% endif %}
                    </div>
                    <div class="col-sm">
                        <form id="preferences_form" action="{% url 'jobs:preferences' %}" method="post" align="center">
                            {% csrf_token %}
                            <input class="btn btn-outline-secondary btn-lg" width="300" height="300"
                                   id="preferences_btn"
                                   type=submit value="Preferencje">
                        </form>
                    </div>
                    <div class="col-sm">
                        <form id="history_form" action="{% url 'jobs:history' %}" method="post" align="left">
                            {% csrf_token %}
                            <input class="btn btn-outline-secondary btn-lg" id="history_btn" type=submit
                                   value="Historia">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>
</html>

mysite/jobs/templates/jobs/inbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inbox</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
<div id="content" class="main">
    <form class="input-group" action="{% url 'jobs:home' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="url" value=""/>
        <input class="btn btn-outline-secondary m-1 mb-1 rounded-1" type="submit" value="Wróć">
    </form>
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="display-3 text-muted" align="center">Nowe oferty</h1>
            <hr class="mt-3 mb-4">

            <br class="mt-5">
            {% if new_offers %}
                {% for offer in new_offers %}
                    <form action="{% url 'jobs:open_offer' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="url" value="{{ offer.offer_url }}"/>
                        <input class="btn btn-outline-secondary rounded-1 input-group mb-3" type="submit"
                               value="{{ offer.offer_title }}">
                    </form>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <br class="mt-3 mb-5">
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>
</html>

mysite/jobs/templates/jobs/open_offer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Open offer</title>
</head>
<body>
    <h1>{{ param }}</h1>
</body>
</html>

mysite/jobs/templates/jobs/preferences.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Preferences</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
<div id="content" class="main">
    <form class="input-group" action="{% url 'jobs:home' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="url" value=""/>
        <input class="btn btn-outline-secondary m-1 mb-1 rounded-1" type="submit" value="Wróć">
    </form>
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="display-3 text-muted" align="center">Preferencje</h1>
            <hr class="mt-3 mb-4">

            <form align="center" action="{% url 'jobs:save_preferences' %}" method="post">
                {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col-sm" align="center">
                            <h2>Lokalizacja</h2>
                            {% for localization in localizations.all %}
                                <div class="input-group-text mt-1">
                                    <div class="p-1">
                                        {% if localization.checked %}
                                            <input type="checkbox" name="localization_choice"
                                                   id="localization{{ forloop.counter }}"
                                                   value="{{ localization.id }}" checked>
                                        {% else %}
                                            <input type="checkbox" name="localization_choice"
                                                   id="localization{{ forloop.counter }}"
                                                   value="{{ localization.id }}">
                                        {% endif %}
                                    </div>
                                    <label for="localization_choice{{ forloop.counter }}">{{ localization.value }}</label>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-sm" align="center">
                            <h2>Stanowisko</h2>
                            {% for role in roles.all %}
                                <div class="input-group-text mt-1">
                                    <div class="p-1">
                                        {% if role.checked %}
                                            <input type="checkbox" name="role_choice" id="role{{ forloop.counter }}"
                                                   value="{{ role.id }}" checked>
                                        {% else %}
                                            <input type="checkbox" name="role_choice" id="role{{ forloop.counter }}"
                                                   value="{{ role.id }}">
                                        {% endif %}
                                    </div>
                                    <label for="role_choice{{ forloop.counter }}">{{ role.name }}</label><br>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-sm" align="center">
                            <h2>Technologia</h2>
                            {% for technology in technologies.all %}
                                <div class="input-group-text mt-1">
                                    <div class="p-1">
                                        {% if technology.checked %}
                                            <input type="checkbox" name="technology_choice"
                                                   id="technology{{ forloop.counter }}"
                                                   value="{{ technology.id }}" checked>
                                        {% else %}
                                            <input type="checkbox" name="technology_choice"
                                                   id="technology{{ forloop.counter }}"
                                                   value="{{ technology.id }}">
                                        {% endif %}
                                    </div>
                                    <label for="technology_choice{{ forloop.counter }}">{{ technology.name }}</label>
                                </div>
                            {% endfor %}
                            <br class="mt-5">
                            <h2>Doświadczenie</h2>
                            {% for exp in experience.all %}
                                <div class="input-group-text mt-1">
                                    <div class="p-1">
                                        {% if exp.checked %}
                                            <input type="checkbox" name="exp_choice" id="exp{{ forloop.counter }}"
                                                   value="{{ exp.id }}" checked>
                                        {% else %}
                                            <input type="checkbox" name="exp_choice" id="exp{{ forloop.counter }}"
                                                   value="{{ exp.id }}">
                                        {% endif %}
                                    </div>
                                    <label for="exp_choice{{ forloop.counter }}">{{ exp.name }}</label><br>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <hr class="mt-3 mb-4">
                <input class="btn btn-secondary btn-lg btn-block" type="submit" value="Zapisz preferencje">
                <hr class="mt-3 mb-5">
            </form>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>
</html>